[package]
name = "propositional-tableau-solver-rs"
version = "0.1.0"
authors = ["许杰友 Jieyou Xu (Joe) <jieyouxu@outlook.com>"]
edition = "2018"

[dev-dependencies]
pretty_assertions = "0.6.1"

[dependencies]

